### ISSUE TITLE
horizontal scroll problems in collapsing toolbar

### ISSUE THREAD

**Issue by zilimojo** [SundeepK/CompactCalendarView#39] opened 2015-11-16 14:49 UTC
I have the calendar view in a collapsing toolbar. The problema I have, is that horizontal scrolling (to change between months) is not smooth, meaning that it gets interrupted by the vertical scroll of the RecyclerView/CollapsingToolbar.
I am not sure where the problema comes from, but probably from this library, because I did not observe this with other calendar views.
(If somebody knows how to fix this but has no time, I probably can try to do it. I just do not know where to start.)

**Comment by SundeepK** [comment] 2015-11-16 15:51
I can have a look at some time and see if I can test it with CollapsingToolbarLayout or RecyclerView and fix the problem. It would be good if you can upload an example but it's not required. Maybe an experiment can be to overide the ``onTouch()``` for RecyclerView for example and disable scrolling to see what happens.

**Comment by SundeepK** [comment] 2015-11-18 11:40
I've had a quick look at CollapsingToolbarLayout, I havn't looked at the android source code for this yet. But my hunch is that CollapsingToolbarLayout doesn't play nice with GestureDetector and it might be something todo with how it handles events inside ``` onInterceptTouchEvent ```.

I never intended it to be used inside a CollapsingToolbarLayout/RecyclerView so it maybe a little more difficult todo. I think maybe embeding the Calendar inside a custom view pager might fix the problem. But I will keep this ticket posted after I look through the android source code.

**Comment by GerritHoekstra** [comment] 2015-11-24 10:06
@zilimojo 
I had also the same problem and I have fixed it with overriding `app:layout_behavior` to my own layout behavior which returns `false` in `onInterceptTouchEvent`. (This disables vertical scroll for the `CollapsingToolbarLayout`)

Demo:
![Demo of the behavior](https://raw.githubusercontent.com/GerritHoekstra/CompactCalendarViewToolbar/master/images/compact-calendar-toolbar-demo.gif)

See for details in this [repository](https://github.com/GerritHoekstra/CompactCalendarViewToolbar/). Specifically [this](https://github.com/GerritHoekstra/CompactCalendarViewToolbar/blob/master/app/src/main/res/layout/activity_main.xml#L34) and [this](https://github.com/GerritHoekstra/CompactCalendarViewToolbar/blob/master/app/src/main/java/com/example/compactcalendarviewtoolbar/ScrollingCalendarBehavior.java#L17) file.

@SundeepK 
Thanks for the great library! I was been searching for some time for a calendar view similar to the Google Calendar app.

**Comment by SundeepK** [comment] 2015-11-24 11:04
Well done! Yes looks like my hunch was right. I was planning to provide a custom Layout to go with the library that overrided the behaviour but you have done some of that work. Many thanks.

I'll spend some time over the weekend to look further into this.

**Comment by SundeepK** [comment] 2016-01-25 13:56
![calendar-animation-optimised](https://cloud.githubusercontent.com/assets/2339563/12552619/c43dc172-c36a-11e5-8f5e-14d81a5ba252.gif)

As an update, I've been experimenting with some animations for opening/closing the calendar. This way you don't necessarily have to embed the calendar within the toolbar. And the you will be able to open/close the calebdar via method call.

Note the gif is slowed down for some reason, possibly when I compressed it, not sure. Might upload a better one when I get time.

**Comment by SundeepK** [comment] 2016-06-22 09:05
I have merge a potentail fix for this bug to master, hopefully it will fix the problem. If anyone is interested, you can important the library locally and test it out. Will release a new version once I have made a few changes to master.

**Comment by SundeepK** [comment] 2016-06-29 23:16
I have released a new version:

```gradle
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.8.5'
}
```

I think this should resolve this issue, have a go and let me know if this works.

**Comment by JulienArzul** [comment] 2016-10-17 14:22
Hello,

I used your Calendar inside a RecyclerView and had the same issue. The fix you applied still prevents vertical scrolling if we're touching inside the CalendarView. The problem is that you're preventing the parent to intercept touch as soon as the CalendarView is touched, no matter if the touch is a simple click, a scroll (vertical or horizontal) or anything else.

To correct that, I've made 2 changes : 
1. For the horizontal scrolling, there is actually a method in View (that appeared in API 14) that sets if a given View can scroll horizontally and fortunately, the ViewPager reads it. We simply need to override the method "canScrollHorizontally" and return true : 
https://developer.android.com/reference/android/view/View.html#canScrollHorizontally(int)

2. For the vertical scrolling, I resolved it using the same trick you used for #82 but limited to a horizontal scroll : when I detect that the Calendar is scrolled horizontally, I prevent the parent to scroll. And I then re-allow it to intercept scrolling when the scroll is finished.

I'll open a Pull-Request with those modifications if you're interested in reviewing them.

**Comment by SundeepK** [comment] 2016-10-17 15:13
@JulienArzul Thanks for the pull request, I've left a comment.

**Comment by SundeepK** [comment] 2016-10-26 13:11
I believe this problem should now be fixed. I have tested this inside a ViewPager andToolbar (as shown above). I'll test inside a RecyclerView at somepoint just to be sure, before releasing a new version. Perhaps, I can add some additional acitivty to the sample to demonstrate that.

**Comment by SundeepK** [comment] 2016-10-27 20:19
Fixed in version:
```gradle
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.9.4'
}

```

**Closed** 2016-10-27 20:19 UTC
Labels: bug
