### ISSUE TITLE
Adding a event with start and end date and time and then showing that time span as selected.

### ISSUE THREAD

**Issue by sarpotdarsaurabh** [SundeepK/CompactCalendarView#173] opened 2017-03-14 10:30 UTC
Can we have a enhancement in this library where we can add an event with start and end time and then that much time span or span between that start date and end will be shown as  selected.?

**Comment by SundeepK** [comment] 2017-03-16 10:30
I think this is a duplicate of #97. It's been open for a while with little progress. That doesn't mean it won't happen. I'm currently working on a backlog of issues so it may take some time. The good thing is that I don't think it's too difficult todo.

**Closed by SundeepK** 2017-03-16 10:30 UTC
