### ISSUE TITLE
Swipe not smooth to move next and previous month

### ISSUE THREAD

**Issue by kprathap23** [SundeepK/CompactCalendarView#45] opened 2015-12-09 06:18 UTC
When i swipe to go next month or previous month. I need drag to the end .

**Comment by XxGoliathusxX** [comment] 2015-12-09 08:31
Thats because your onMonthScroll() -method. Can you post your code?

**Comment by kprathap23** [comment] 2015-12-09 08:42
I have an asyncTask calling webservice to get the eventList for every month

**Comment by SundeepK** [comment] 2015-12-11 14:18
Hi, can you post some sample code of you onMonthScroll listener? Is there actuall *lag* when scrolling or is the scrolling to rigid?

**Comment by GerritHoekstra** [comment] 2015-12-13 16:45
I think he means that the scrolling is too rigid. I've the same user experience, I am used to the `ViewPager` swiping (a fast swipe is sufficient, I don't have to dag from start to end for example)

**Comment by SundeepK** [comment] 2015-12-14 00:34
Thanks that makes sense, will look at OverScroller documentation and see what I can find.

**Comment by GerritHoekstra** [comment] 2015-12-14 12:25
I think we'll need [VelocityTracker](http://developer.android.com/training/gestures/movement.html#velocity) for this. Take a look at this: http://www.devexchanges.info/2015/03/create-snapping-horizontal-scroll-view.html

**Comment by SundeepK** [comment] 2015-12-18 10:17
If any one is interested there is some code changes in a [branch](https://github.com/SundeepK/CompactCalendarView/tree/%40wip/experimental_changes_scrolling). It would be good t get some feedback on how it feels. It should work very simialr to the one Google calendar. Simply checkout the project, run the sample and have a play around witht the scrolling.

**Comment by GerritHoekstra** [comment] 2015-12-18 11:23
I've tested and I can confirm that it feels just like the Google Calendar (or any ViewPager). Only the `onDayClick` is broken now (I've tested it in the [toolbar](https://github.com/SundeepK/CompactCalendarView/issues/39#issuecomment-159215221)).

If you need more feedback I've a list:
* Lowering  the `minSdkVersion` to 14. (My project depends on `minSdkVersion` 14)
* `compileSdkVersion` can be 23, `buildToolsVersion` can be 23.0.2 and `targetSdkVersion` can be 23
* If the above is done then it's possible to `compile 'com.android.support:appcompat-v7:23.1.1'`
* Week numbers before the week (just like Google Calendar) if the screen width is 
wide enough:
![week_numbers](https://cloud.githubusercontent.com/assets/3610345/11895472/4b5e00a4-a57f-11e5-9588-e9a7f30cdfa4.png)
* Make a option to auto re-size (`onMeasure`) when a month is scrolled so that the height of the calendar view equals the current month (for example the height of February 2016 can be smaller by one row)
* Show only a range of dates (https://github.com/SundeepK/CompactCalendarView/pull/37) and use use the `springBack()` method in `OverScroller`, which returns the previous month to the normal coordinate range in case it went out of bounds.

Thanks for the great library!

**Comment by SundeepK** [comment] 2015-12-18 11:38
> Only the onDayClick is broken now (I've tested it in the toolbar).

Yep will have a look, I wanted to make sure people are happy with the scrolling now.

> Lowering the minSdkVersion to 14. (My project depends on minSdkVersion 14)
> compileSdkVersion can be 23, buildToolsVersion can be 23.0.2 and targetSdkVersion can be 23

Should be easy enough.

> Week numbers before the week (just like Google Calendar) if the screen width is wide enough:

Interesting, I havn't seen this on my phone. And im using a phone with a high res, is that using a tablet or something?

> Make a option to auto re-size (onMeasure) when a month is scrolled so that the height of the calendar view equals the current month (for example the height of February 2016 can be smaller by one row)

Never been a fan of that. So I never added it, but if enough people want it. I can do it.

> Show only a range of dates (#37) and use use the springBack() method in OverScroller, which returns the previous month to the normal coordinate range in case it went out of bounds.

Will have a look at that as well since people seem to want ti.

So theres a few issues that need to be raised as a result I think. Will do so when I get time.

**Comment by GerritHoekstra** [comment] 2015-12-18 11:55
> Interesting, I havn't seen this on my phone. And im using a phone with a high res, is that using a tablet or something?

I'm using a Nexus 5 with Android 6.0.1 (maybe it's only on Marshmallow but I'm not sure). My Google Calendar version is: 5.3-108865406-release

> Never been a fan of that. So I never added it, but if enough people want it. I can do it.

I'm also not a fan of it, but I think some people want the same behavior as the Google Calendar.

Take your time!

**Comment by GerritHoekstra** [comment] 2015-12-19 11:16
I discovered some bugs:

With the [latest version](https://github.com/SundeepK/CompactCalendarView/commit/c862a73ec1fef54202e7b0d274b97d45104dbb69):
* `onDayClick` is working but the snapping is broken if we do a 'long' duration swipe.

With the [previous version](https://github.com/SundeepK/CompactCalendarView/commit/f10e8dab8e065480e17d031d0216a1145c49f71f):
* If we doing a 'long' duration swipe from the end to start (so that the next month is visble) it snaps still on the previous month.

On all versions:
* If we are setting the current date (`setCurrentDate(new Date()`); the current date is also visible in the same month on the year 2014, 2016 etc. (it looks like the `Calendar.YEAR` is not checked or forgotten)

**Comment by SundeepK** [comment] 2015-12-22 13:11
> With the latest version:
> 
> onDayClick is working but the snapping is broken if we do a 'long' duration swipe.
> With the previous version:
> 
> If we doing a 'long' duration swipe from the end to start (so that the next month is visible) it snaps still on the previous month.

These should now be fixed. I've made some changes that seem good to me in my initial testing. Have a go and let me know your thoughts. Thanks for the feedback so far.

> On all versions:
> 
> If we are setting the current date (setCurrentDate(new Date()); the current date is also visible in the same month on the year 2014, 2016 etc. (it looks like the Calendar.YEAR is not checked or forgotten)

This is actually a feature of Google calendars, so I did the same thing.

**Comment by MonkeyLaboratories** [comment] 2016-01-02 05:27
Scrolling is completely broken now, I implemented the test branch and also tried your sample code and have confirmed you can't scroll.

**Comment by SundeepK** [comment] 2016-01-02 12:54
Sorry about that, I had made some slight re-factoring and didn't run the sample before assuming it would work :weary:. Try again now, I've run the sample and tested it.

As far as I can see, the only thing that needs to be changed is that if the user has scrolled slowly to the end of the current calendar, it snaps back rather than scroll to the next. However, this shouldn't be too difficult to fix I don't think.

**Comment by MonkeyLaboratories** [comment] 2016-01-02 17:40
Awesome, It's working great now thanks! I'll investigate the snap back when slowly scrolling and I'll keep you updated.

**Comment by GerritHoekstra** [comment] 2016-01-03 14:43
> This is actually a feature of Google calendars, so I did the same thing.

My Google Calendar doesn't show this 'feature' see this:
![Feature](https://cloud.githubusercontent.com/assets/3610345/12079148/d8da86da-b22e-11e5-83ee-8d721757bd8b.gif)

I discovered some bugs with the latest version:

If we press on day, it first selects the first day of the month and then the day we clicked on (I don't know if this was also in the previous version, I just discovered this while testing the `onDayClick`, it looks like the `onMonthScroll` gets first called if we touch something):
![Bug 1](https://cloud.githubusercontent.com/assets/3610345/12079152/0c1f72c6-b22f-11e5-8698-e175adbb97a8.gif)

And the bug that has been discussed here before (scroll slowly to the end of the current calendar, it snaps back rather than scroll to the next):
![Bug 2](https://cloud.githubusercontent.com/assets/3610345/12079154/41729a52-b22f-11e5-8d58-2e8fb53fd4d5.gif)

(Sorry for the many animated gifs, I thought that this would help to clarify)

**Comment by SundeepK** [comment] 2016-01-03 15:04
Thanks for the gifs, very helpful.

> This is actually a feature of Google calendars, so I did the same thing.
> My Google Calendar doesn't show this 'feature' see this:

Interesting, when I was developing the initial calendar, it was how it worked. I guess maybe they changed it or I may have been mistaken. Either way, we need to also check the year before drawing the indicator which should fix the problem. 

> If we press on day, it first selects the first day of the month and then the day we clicked on (I don't know if this was also in the previous version, I just discovered this while testing the onDayClick, it looks like the onMonthScroll gets first called if we touch something):

Nice catch there, looks like a bug. The onMonthScroll should not be called. I'll update the unit tests to verify its not called on when a day is selected and fix the bug. Looks like I didn't notice it on my device maybe because it renders things too fast.


> And the bug that has been discussed here before (scroll slowly to the end of the current calendar, it snaps back rather than scroll to the next):

Thanks, for clarifying with a gif :).

**Comment by SundeepK** [comment] 2016-01-03 19:54
> If we press on day, it first selects the first day of the month and then the day we clicked on (I don't know if this was also in the previous version, I just discovered this while testing the onDayClick, it looks like the onMonthScroll gets first called if we touch something):

I've updated the code to fix this problem and added some android instrumentation tests for this case (along side the unit tests). 

> And the bug that has been discussed here before (scroll slowly to the end of the current calendar, it snaps back rather than scroll to the next):

Will look into this over the next day or so.

**Comment by SundeepK** [comment] 2016-01-14 23:53
> And the bug that has been discussed here before (scroll slowly to the end of the current calendar, it snaps back rather than scroll to the next):

I added some code to handle this case also now, I've tested on a phone and it seems to be ok. Might need a bit more tweaking though if it doesn't feel right.

**Comment by SundeepK** [comment] 2016-01-21 00:04
I've tested the scrolling on 2 different devices and it seems good. I couldn't get it to break or do anything odd. Would be good to get a final bit of feedback on this. Alternatively I could release it under a beta release so people can start using it.

**Comment by GerritHoekstra** [comment] 2016-01-21 17:24
Sorry I've taken so long to reply. I've tested and it seems to be good. But it feels somewhat weird because there is no 'switch transition' when we scroll slowly to the end of the current calendar. 
At first look into the code it seems that `(int) (Math.abs((int) ( remainingScrollAfterFingerLifted))  / (float) width * ANIMATION_SCREEN_SET_DURATION_MILLIS)` on line 425 returns 0 when we call it in `scrollNextMonth`. (I'm not sure, but it seems the most logical)

A beta (or a snapshot using Sonatype's snapshots repository) would be nice.

**Comment by SundeepK** [comment] 2016-01-21 18:33
Would you mind uploading a gif of what you mean? It should smooth scroll  to next month for example if you slowly scroll 75% of the width of the current calendar. Regardless of velocity.

**Comment by GerritHoekstra** [comment] 2016-01-21 18:42
This is what I mean (instead of a smooth transition it goes directly to the next month):
![bug](https://cloud.githubusercontent.com/assets/3610345/12490626/c4d33b72-c076-11e5-922d-d456537ce819.gif)

**Comment by SundeepK** [comment] 2016-01-21 18:45
That's weird. That's exactly what I fixed. Maybe I made a mistakes with some commits will check when I get time today.

**Comment by SundeepK** [comment] 2016-01-22 00:13
![](http://im2.ezgif.com/tmp/ezgif-1569790379.gif)

I've debugged the sample app on my phone and uploaded the gif. It does give a transition from what I could see. I could increase the animation duration a bit though to make it more noticeable.

I'm not sure why you are not seeing the transition to the prev/next month though.

**Comment by GerritHoekstra** [comment] 2016-01-22 08:33
Sorry it was my fault. I had this in my `onMonthScroll`:
```java
@Override
public void onMonthScroll(Date firstDayOfNewMonth) {
    if (mCalendarView != null) {
        mCalendarView.setCurrentDate(firstDayOfNewMonth);
    }
}
```

That was causing that there was no transition. It's working fine when I delete that code.

Maybe it should wait for the OverScroller to be finished before calling `performMonthScrollCallback()` (don't know how to accomplish this, could not find any callback we can override in OverScroller)

**Comment by SundeepK** [comment] 2016-01-22 14:17
Ok will look through OverScroller code for this to understand it a little better.

On a side note, you do not need to call ```mCalendarView.setCurrentDate(firstDayOfNewMonth); ``` because the calendar will automtically be set to the firstDayOfNewMonth for you.

**Comment by SundeepK** [comment] 2016-02-05 00:19
```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.8.2-beta-smooth-scrolling'
}
```
New  beta smooth scrolling version. I plan to make another version available that allows people to make various things a bit more configurable.

**Comment by kprathap23** [comment] 2016-03-31 10:14
works pretty good.
Great Work.Thanks

**Comment by SundeepK** [comment] 2016-04-12 13:26
Merged changes to master. Will release soon and update as a comment, closing this issue now.

**Closed by SundeepK** 2016-04-12 13:26 UTC
Labels: enhancement

**Comment by SundeepK** [comment] 2016-04-16 21:15
```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.8.3'
}

```
