### ISSUE TITLE
Current Day Bg can be changed but not the text color.

### ISSUE THREAD

**Issue by Malikkhoja** [SundeepK/CompactCalendarView#144] opened 2016-12-29 10:28 UTC
The current lib does not allow user to change the current date text color however its background can be changed.

**Comment by SundeepK** [comment] 2017-01-01 16:02
Hi this is a duplicate of #125. Closing as duplicate. I'm am currently working through a backlog of enhancements. I will surely get around to it at some point.

**Closed by SundeepK** 2017-01-01 16:02 UTC

**Comment by wowlocal** [comment] 2017-04-28 09:20
![image](https://cloud.githubusercontent.com/assets/17961162/25522842/181f2ff4-2c0d-11e7-8103-4a1aee1984ec.png)
