### ISSUE TITLE
Lag tapping on days?

### ISSUE THREAD

**Issue by xbroak** [SundeepK/CompactCalendarView#18] opened 2015-09-07 13:47 UTC
Is this intentional? Tapping on a day has a short delay before actually changing day

**Comment by SundeepK** [comment] 2015-09-07 13:59
I'll have to run the example that's shipped with the code to test things out when I get the time, but what version are you running? Are you on the latest?

**Comment by xbroak** [comment] 2015-09-07 13:59
Yep, latest!

**Comment by SundeepK** [comment] 2015-09-07 15:30
Ok thanks. There is a slight bit of lag clicking days, it's something that I wanted to looks at for a while. There's some calculations that are running to find the correct day that was click. The only things I can do is run some android code profiling commands to figure out where most of the cpu time is spent. I have a suspicion though that the calendar is being redrawn an extra time than needed. So instead of drawing once, it draws twice.

**Comment by SundeepK** [comment] 2015-09-07 21:31
So after a little investigation and profiling, the code doesn't look like it's actually slow or drawing unnecessarily. However, I am using GestureDetector.SimpleOnGestureListener to listen for onSingleTapConfirmed event. Looking through android source code, basically, GestureDetectorCompat android will wait for some time until an event is considered a single tap event. This time is what you see as the lag.

As an experiment, you can move the code from onSingleTapConfirmed method to on down in the CompactCalendar class. You will see that the UI updates immediately. However, this causes other issues with scrolling and oddities with gesture detection.

java ```

        @Override
        public boolean onSingleTapConfirmed(MotionEvent e) {
//            Date onDateClicked = compactCalendarController.onSingleTapConfirmed(e);
//            invalidate();
//            if(listener != null){
//                listener.onDayClick(onDateClicked);
//            }
            return super.onSingleTapConfirmed(e);
        }

        @Override
        public boolean onDown(MotionEvent e) {
            Date onDateClicked = compactCalendarController.onSingleTapConfirmed(e);
            invalidate();
            if(listener != null){
                listener.onDayClick(onDateClicked);
            }
            return compactCalendarController.onDown(e);
        }

```

So the fix? Well I can see implementing custom gesture detection as one way of doing things without much thought. But I'll have to think about this a little bit :)

**Comment by spartacusrex99** [comment] 2016-04-11 09:59
There is a much easier fix..

Switch OnSingleTapConfirmed for onSingleTapUp.. 

OnSingleTapConfirmed waits to make sure you are not double clicking.

**Comment by SundeepK** [comment] 2016-04-12 13:27
Thanks for the comment, I'll investigate this soon then.

**Comment by yoavst** [comment] 2016-10-27 19:07
@spartacusrex99 fix is great, but why isn't it integrated? your commit is from april.

**Comment by SundeepK** [comment] 2016-11-08 12:34
@yoavst Mostly because I have been implementing other feature and enhacements. There is some pull request I want to merge before. Once that feature is merged I will have a look at this.

**Comment by yoavst** [comment] 2016-11-08 14:40
Thanks! Currently I'm not using this library, but I'll be happy to use this library for performance reason.

**Comment by SundeepK** [comment] 2016-11-28 13:20
Merged will release a new version some time in the next few days.

**Closed by SundeepK** 2016-11-28 13:20 UTC
Labels: enhancement
