### ISSUE TITLE
How to forbid first day as select in each month when scroll to change mothe

### ISSUE THREAD

**Issue by carl1990** [SundeepK/CompactCalendarView#137] opened 2016-12-16 09:29 UTC
when I scroll to next or last month this month first day will be marked select.
how can I forbid it

**Comment by SundeepK** [comment] 2016-12-16 10:14
Seems like a duplicate of #90. I'll try and have a look in the upcoming week, it's been a long standing feature request :)

**Closed by SundeepK** 2016-12-16 10:14 UTC
