### ISSUE TITLE
Current day is not refreshing when dateTime is changed via system preferences.

### ISSUE THREAD

**Issue by Heroo** [SundeepK/CompactCalendarView#58] opened 2016-03-21 09:54 UTC
Current day is not updated after manually changed date on the phone. Using setCurrentDate(Date dateTimeMonth) in onResume() method is not helping. Is there a way to refresh current day?

**Comment by SundeepK** [comment] 2016-03-21 10:18
Ah interesting testcase scenario. Could you give me more exact infomation on the steps you did to cause this and what version as well please? From what I understand this is what you described:

1. Launch sample
2. Minimise app
3. Change current system datetime to yesturday
4. Resume app
5. The current date is not change to the system datetime?

Thanks.

**Comment by SundeepK** [comment] 2016-03-22 09:57
I've tried this out and I can confirm that is a problem. I'll look into this. Maybe we need to listen for dateTime changes and then update current date accordingly?

**Comment by schmidan** [comment] 2016-07-22 11:15
Am i correct in that this also happens on normal time progression?
So when a activity using this widgets does not get killed for multiple days the today indicator never gets updated?

**Comment by SundeepK** [comment] 2016-07-22 12:29
Yeah, I don't think it would. But that is easily solved by overriding `onResume` method in your activity and calling `setCurrentDate` on the calendar to update the current date.

**Comment by schmidan** [comment] 2016-07-22 13:55
setCurrentDate does not help to reset the (default) yellow Today bubble for me. should it?

I did override onResume and use setCurrentDate regularly to move the (default) blue indicator on recyclerview scrolls but the today indicator does not update.

**Comment by SundeepK** [comment] 2016-07-22 14:08
Ahh, I see what you mean. Yes, I think it might be a bug in the code in that case. But the good thing is that it should be a single line change hopefully. The calendar stores 2 different `Calendar` instances. One for the current selected day that the user can select when clicking on a date and the one which you can set via `setCurrentDate`. 

Then theres the one which stores what the actual today date is so that it can draw that indicator. The code should re-initalise that date also. which I believe should be simple as `todayCalender = Calendar.getInstance(locale);` in the `setCurrentDate` method so that both internal calendars are updated.

**Comment by schmidan** [comment] 2016-07-22 14:45
Yes, i believe so as well. Had a quick glance at the code. hope to maybe get around to fork it next week (or are you about to upgrade yourself?).

**Comment by SundeepK** [comment] 2016-07-24 23:34
Released under:
```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.8.8'
}
```
Now `setCurrentDate` will correctly update the current day indicator.

**Comment by SundeepK** [comment] 2016-08-15 12:36
Closing this issue since it has been fixed by simply setting the date `onResume`

**Closed by SundeepK** 2016-08-15 12:36 UTC
Labels: bug
