### ISSUE TITLE
Show Event indicators to currently selected day

### ISSUE THREAD

**Issue by VishnuTB** [SundeepK/CompactCalendarView#73] opened 2016-05-30 05:13 UTC
While Adding events to current date, the background color overlaps and the small indicators are not displayed.
I tried to change the  `app:compactCalendarCurrentDayBackgroundColor="#2bb573"` to transparent but its not working either.
Is there any way to display small indicators on current day?

**Comment by SundeepK** [comment] 2016-05-30 20:39
This is actually how google calendars works as well, and is expected behaviour (it has also been raised before). Since this library is based on that, it has inherited that functionality as well. I can see this being a problem for some people, but showing event indicators along with the larger indicator for the day looks odd if its overlayed on top of it. 

Of course , the alternative is to just draw the event indicators lower so both can be displayed. But I haven't really tried that yet. I'm open to suggestions of what people think would be nice.

**Comment by XxGoliathusxX** [comment] 2016-05-31 00:36
I made him aware of this already. 
It seems not like he will change this behavior.

**Comment by VishnuTB** [comment] 2016-05-31 04:46
is there any way to display the event markers **on top of the current day** indicator?

**Comment by SundeepK** [comment] 2016-05-31 09:19
Yes, you can fork the code and change the line:

https://github.com/SundeepK/CompactCalendarView/blob/master/library/src/main/java/com/github/sundeepk/compactcalendarview/CompactCalendarController.java#L755

And remove the `!isSameDayAsCurrentDay && !isCurrentSelectedDay` check in the if statement. I think that should draw indicators for you on the current selected day. I can upload a screenshot of what it will look like, but I don't think it will look very presentable.

**Comment by tryadelion** [comment] 2016-06-28 06:13
could this be setup up as an enhacement?   if it's just a line , a boolean that by default doesn't show them above and a .setShowMarkersAboveSelectors would suffice

**Comment by SundeepK** [comment] 2016-06-29 09:53
Yes, the acutal change is not too difficult. It does mean that the small indicators need to be drawn lower than they already are, which would mean each day is display with a larger height. The other thing is that many people want to customise things very differently. I was thinking about setting up a builder patter so that people can pick and choose how things are set up and set it in the calendar. Otherwse there will be many boolean fields setup in the calendar which can get ugly. But this requires some design.

**Comment by useitsoftware** [comment] 2016-09-02 07:58
any update?

**Comment by SundeepK** [comment] 2016-09-02 09:31
@useitsoftware Sorry, unfortunately no update as of yet. I'm currently working on other enhancements that more people may benifit from. I'm not sure when I wil get around to this as there is a backlog of enhancements to make.

**Comment by SundeepK** [comment] 2016-09-07 12:40
Hi all, what should be the expected look and feel for this? I think the current selected day should simply offset the the event indicators just below it. With this way, however, I will need to adjust indicator heights and it may require the calendar to have a slightly higher height as well in the xml properties to make it look ok.

**Comment by tryadelion** [comment] 2016-09-08 08:20
either just below, or , the same way as other days, but over the "selected" color. maybe with a modifiable-color 1dp border on the event indicators?

**Comment by SundeepK** [comment] 2016-09-13 12:18
Here's what I have below. The events are just below the selected day and will be configurable via a property.

![eventsbelow2-small](https://cloud.githubusercontent.com/assets/2339563/18473215/a2998614-79b3-11e6-954a-2cc811fe8579.png)
![eventsbelow-small](https://cloud.githubusercontent.com/assets/2339563/18473214/a2967244-79b3-11e6-830d-7956c9824b87.png)

If you want to display events below the selected day, then the selected day indicator will be scaled by 10% to make enough space to draw the events below. It seems to look ok. If you dont enable the property, then the will be drawn with no scalling applied. You can however just increase the height of the calendar by 10px to increase the size of the indicators if you think it looks too small. It look like its cutting it close in picture 2. Where the selected day is light red and current day is darker red.

Does any one have any thought?

**Comment by XxGoliathusxX** [comment] 2016-09-13 16:17
Thats a good solution!

**Comment by tryadelion** [comment] 2016-09-14 09:12
yeah, awesome solution.

**Comment by SundeepK** [comment] 2016-09-14 10:46
Hi guys, thanks for the updates. I will release a new version after some testing but that will be atleast a week from now since I will be off on holiday. Sorry about the delays.

**Comment by tryadelion** [comment] 2016-09-14 10:47
have a nice holiday!

**Comment by SundeepK** [comment] 2016-09-26 11:41
Just an update, I'm working on some unit tests for this functionality. Will give an update once thats done soon.

**Comment by XxGoliathusxX** [comment] 2016-10-03 15:32
How is it going?

**Comment by SundeepK** [comment] 2016-10-03 16:18
Sorry for the delay, I have been pretty busy. I have most of the code done I beleive. I want to release a testing release in the next few days so that feedback can be provided.

**Comment by SundeepK** [comment] 2016-10-07 10:17
Hi guys, so I'll be releasing a beta version today hopefully if anyone is interested in trying it out to give any feedback. I also updated the build.gradles to target the latest android version and updated dependecies. Hence why it took longer than expected. 

Any takers?

**Comment by XxGoliathusxX** [comment] 2016-10-07 18:05
if you give me a compile i will test it out on my marshmallow 6.0.1

**Comment by SundeepK** [comment] 2016-10-07 23:40
I've released a new beta version:

```gradle
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.9.1'
}
```
Let me know if you have any feedback. You can apply the desired functionality by calling method `shouldDrawIndicatorsBelowSelectedDays(true)`

**Comment by XxGoliathusxX** [comment] 2016-10-08 18:50
It works! This is a big improvement. I have one question. if I remove one item from a day how to update the small indicators? Example: 4th June: 2 Events with 2 Indicators. I remove one. How to show without clicking anywhere the amount of the indicators?

**Comment by tryadelion** [comment] 2016-10-10 08:17
i will check it as soon as i can on a DEV environement and provide you feedback!

**Comment by SundeepK** [comment] 2016-10-10 13:07
Thanks, I'll release a new version if there is no other feedback.

**Comment by tryadelion** [comment] 2016-10-13 09:54
still on it, haven't had time to try it yet. will provide feedback before saturday night.

**Comment by SundeepK** [comment] 2016-10-17 09:47
@tryadelion Did you have a chance to give the beta a go? If you don't have the time, don't worry about it. I'd like to get this functionality out because it's long time standing.

**Comment by tryadelion** [comment] 2016-10-17 09:55
it worked nice for me, sorry for not posting. release it ^^

**Comment by SundeepK** [comment] 2016-10-17 10:04
👍 Many thanks, will release a new version today then.

**Comment by SundeepK** [comment] 2016-10-17 23:23
New version below:
```gradle
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.9.2'
}
```

**Comment by ranveeraggarwal** [comment] 2016-10-22 10:19
I love this functionality and I had been looking for it for a while. There is a small problem though. This is what happens when I used the calendar with a height of `320dp` on a Nexus 5X (API Level 24). When I tone it down to `260dp`, however, it looks exactly as above. Can something be done about this?
![14800323_1401199066576831_1942781884_o](https://cloud.githubusercontent.com/assets/3941281/19618663/971f0730-986e-11e6-8d49-837a54f45c50.jpeg)

**Comment by SundeepK** [comment] 2016-10-22 17:35
Hi @ranveeraggarwal this is most defiantly a bug. Basically, I think the small indicators are not being offset with respect to how big the larger indicator is. I think I'll need to take into account the size of the large indicator or height per day. Should not be too difficult.

**Comment by ranveeraggarwal** [comment] 2016-10-22 18:50
@SundeepK why don't you allow the small indicators to come on top of the larger one? That should look fine, IMHO.

**Comment by SundeepK** [comment] 2016-10-23 00:58
@ranveeraggarwal I think that's a good idea to create a new issue for that, might be a good idea to fix what we currently have.

**Comment by SundeepK** [comment] 2016-10-23 01:02
@ranveeraggarwal try this version:

```gradle
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.9.3'
}
```
I tested it on an emulator for nexus 5 api 23 and nexus 6p 7.1.1 phone. I also added a unit test so that I know if this functionality will break in the future.

**Comment by ranveeraggarwal** [comment] 2016-10-23 05:40
@SundeepK it now has an alignment problem. 
![screenshot_20161023-110631 copy](https://cloud.githubusercontent.com/assets/3941281/19624368/fd24ac36-9910-11e6-84b8-3a6e1bc5ff15.png)
Can you try putting the smaller indicators on top (z-value wise) of the larger ones, such that they are all aligned on to the same line?

**Comment by SundeepK** [comment] 2016-10-23 15:06
@ranveeraggarwal That is expected, it will just displace the small indicators when that day is selected. As Mentioned previously, I raised a new issue #121 for this case. Looks like it now works for larger heights so I'll close this issue so that you can track comments on that new issue raised.

**Closed by SundeepK** 2016-10-23 15:06 UTC
Labels: enhancement

**Comment by ranveeraggarwal** [comment] 2016-10-23 15:19
@SundeepK sounds great 😄

**Comment by saprahits** [comment] 2018-02-10 05:59
How to Table format Show Calendar.. help me

**Comment by ABr751** [comment] 2018-02-20 06:04
need to show the event indicator above the dates!!!!.any way??????

**Comment by JDangar** [comment] 2018-07-26 05:37
@SundeepK How can I disable previous and future dates from current date in CompactCalendarView?
