### ISSUE TITLE
Want to add drawable icons insteadof colorful dots

### ISSUE THREAD

**Issue by anshulpatro** [SundeepK/CompactCalendarView#193] opened 2017-05-03 08:55 UTC
I want to add some drawable icons instead of colorful dots to represent an event. 

Is this possible ?

I tries this, but it didn't worked 

    new Event(R.drawable.ic_checked, timeInMillis, "Event at " + new Date(timeInMillis)),

**Comment by SundeepK** [comment] 2017-05-03 15:59
This is a duplicate of #181. Have a read through and let me know if you don't understand. Short version is, not currently supported. If you want it, you can fork the code and the part where the dot is drawn, you can just draw your icon instead.

**Comment by anshulpatro** [comment] 2017-05-04 05:13
Still confused, like I have some drawable icons. How can I place them in
the calendar

**Comment by SundeepK** [comment] 2017-07-12 21:40
Hi, did you manage to solve this problem? Do you still need help with this? I can perhaps have a look at creating some sample code if you still need it.

**Comment by anshulpatro** [comment] 2017-07-13 04:13
It would be great if you can share some sample code

**Comment by SundeepK** [comment] 2017-07-13 12:11
Ok thanks, will try get something for you soon.

**Comment by SundeepK** [comment] 2017-07-16 22:45
Have a look at issue #181.

**Closed by SundeepK** 2017-07-16 22:45 UTC

**Comment by anshulpatro** [comment] 2017-07-18 23:58
thanks,


this worked for me :)
