### ISSUE TITLE
onMonthScroll scrolling fast damages the year of the parameter firstDayOfMonth

### ISSUE THREAD

**Issue by carlastabile** [SundeepK/CompactCalendarView#41] opened 2015-11-25 21:49 UTC
Hi. I just realized that when you scroll kind of fast between months till another and another year, the date given in the onMonthScroll argument starts to give the wrong year. I scrolled till December 2018 and then went back to December of the last year (2017) and it shows 2020 or any other year not even close. 

If I keep scrolling between months, the year of the Date gets even more wrong. 

I tried my best to explain this and I know its not very common to scroll like that but it is still an issue. Hope you can solve it soon.

**Comment by SundeepK** [comment] 2015-11-25 22:10
Are you on the latest version? I have tried to reproduce this, but I'm finding it difficult to do so. Are you using the sample or have you modified any thing?

**Comment by carlastabile** [comment] 2015-11-25 22:15
@SundeepK I'm using version 1.7.9. I know its hard to reproduce it and it doesn't happen all the time. It is really really weird you need to scroll like 12 months away to start seeing it.

**Comment by SundeepK** [comment] 2015-11-25 22:16
I have scrolled years and haven't spotted it, you are using the sample project correct?

**Comment by carlastabile** [comment] 2015-11-25 22:17
@SundeepK this is my code: 


     calendarView.setListener(new CompactCalendarView.CompactCalendarViewListener() {
            @Override
            public void onDayClick(Date dateClicked) {
                currentSelectedDate = dateClicked;
                dateSelected.setText(DateUtil.getCalendarShowableDate(dateClicked));
            }

            @Override
            public void onMonthScroll(Date firstDayOfNewMonth) {
                setMonthName(dateFormatForMonth.format(firstDayOfNewMonth)); //here I'm showing month and year in the Toolbar

                Calendar scrolledCalendar = Calendar.getInstance();
                scrolledCalendar.setTime(firstDayOfNewMonth);

                todayCal = Calendar.getInstance(Locale.getDefault());

                //If I scrolled to the current month, set the day to the current day
                if (todayCal.get(Calendar.MONTH) == scrolledCalendar.get(Calendar.MONTH) &&
                        todayCal.get(Calendar.YEAR) == scrolledCalendar.get(Calendar.YEAR)) {
                    scrolledCalendar.set(Calendar.DAY_OF_MONTH, CalendarContainer.this.todayCal.get(Calendar.DAY_OF_MONTH));
                    calendarView.setCurrentDate(scrolledCalendar.getTime());
                }
                dateSelected.setText(DateUtil.getCalendarShowableDate(scrolledCalendar.getTime()));
                presenter.getEventsByStartDate(scrolledCalendar.getTime());
            }
        });

**Comment by SundeepK** [comment] 2015-11-25 22:21
I suspect a bug on setting the current date using ``` setCurrentDate() ``` whilst in the callback.

**Comment by carlastabile** [comment] 2015-11-25 22:27
@SundeepK Do you mean I can't call setcurrentDate inside the onMonthScroll? Sorry, I didn't understand that last comment.

**Comment by SundeepK** [comment] 2015-11-25 22:47
Well it might be a bug in the library when setting the current day whilst in the callback. Under the hood, it uses java Calendar object, which is not the nicest class you work with and is mutable. Might be some inconsistency while setting the date which could be causing the problem, but I will investigate. 

I have copied your code directly and I can see the bug as you describe.

**Comment by SundeepK** [comment] 2015-11-25 23:36
Ok I think I found the problem, under the hood, the library uses OverScroller to keep track of how far the user has scrolled in x direction. When setting the date, the current date was being initialized correctly with the one passed in but the OverScroller current x direction was not being reset to 0. 

This causes a problem since internally it uses OverScroller is used to keep track how many months user has scrolled in +/- sets the date accordingly.

**Comment by SundeepK** [comment] 2015-11-26 00:39
This also leads to anther method to be exposed by the library which is ``` scrollBackToCurrentDate() ```. This will allow user to easily scroll back to the currently set date in the calendar through ```         scroller.startScroll((int) accumulatedScrollOffset.x,0, (int) - accumulatedScrollOffset.x,0); ``` and will play an animation. But this is totally out of scope of this issue.

**Comment by SundeepK** [comment] 2015-11-28 20:18
After a bit of playing around, I've taken the pragmatic approach by simply calling ``` scroller.startScroll(0,0,0,0); ``` to fix the bug. However, this doesn't have the nicest effect since it makes the calender reset its X position to 0 with a really quick scrolling animation . Unfortunately, the ``` OverScroller `` class provided in the Android SDK doesn't allow you to simply set an X value without scroll, which is annoying.

I will have another look at refining this, but I much rather fix the problem than have it perfect.

**Comment by SundeepK** [comment] 2015-11-28 20:25
Changes are in master, will be released in the next day.

**Comment by SundeepK** [comment] 2015-11-28 20:49
Re-opening until I actually release a new version so other people can see the issue.

**Comment by SundeepK** [comment] 2015-11-29 23:47
Available in version:

``` 
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.8.0'
}
```

**Closed by SundeepK** 2015-11-29 23:47 UTC
Labels: bug
